### PR TITLE
Add Log::CommandLine

### PR DESCRIPTION
**Pull request by CurtTilmes**
Use some command line options to set up the logger a bit

./someprogram --debug --logcolor --logfile=/var/log/mylogfile

### CODE REVIEW

**Comment by bduggan** [comment]
Thanks!  Looks neat.  But, here's what happened when I tried it:
```
$ cat cli.p6
#!/usr/bin/env perl6

use Log::CommandLine;

warning 'hi';

$ perl6 -Ilib cli.p6
===SORRY!===
No such method 'close-taps' for invocant of type 'Any'
```
Adding `use Log::Async` removed the error, but didn't print "hi".

Also this needs tests.

I don't think `Terminal::ANSIColor` should be a requirement of Log::Async -- could this work without  having Terminal::ANSIColor installed?  (unless --logcolor is given of course)
 
Also, I think this should be `Log::Async::CommandLine`.

**Comment by CurtTilmes** [comment]
The not printing is a general problem with Log::Async -- the program will end even if there are logs "in the pipe".  Put a sleep 1 at the end and you'll always get the last few prints..

Could you add some sort of phaser call in Log::Async that will make sure everything gets pushed through at the exit of the program?

Should be able to use Terminal::ANSIColor iff --logcolor

Should be renamed to Log::Async::CommandLine

**Comment by CurtTilmes** [comment]
Renamed to Log::Async::CommandLine and put "use Terminal::ANSIColor" inside the --logcolor conditional.

**Comment by bduggan** [comment]
Hmm...still getting errors when I don't have Terminal::ANSIColor installed.

**Comment by CurtTilmes** [comment]
Yeah, looks like 'use' is compile time -- I'll have to EVAL() to compile the other code at runtime iff you use the --logcolor option.

**Comment by CurtTilmes** [comment]
Removed Terminal::ANSIColor entirely.

**Comment by bduggan-picwell** [comment]
> Could you add some sort of phaser call in Log::Async that will make sure everything gets pushed
> through at the exit of the program?

#5 should take care of this.

**Comment by bduggan** [comment]
This is looking good, just needs some tests.

**Comment by CurtTilmes** [comment]
Added some tests for command line options.

**Pull request merged**
